version: '3.8'
services:
  fluentd:
    build: ./
    # command: ["tail","-f","/dev/null"]
    volumes:
      - ./config:/fluentd/etc
     env_file:
      - .env
    ports:
      - "14224:14224"
      - "14224:14224/udp"
      - "24224:24224"
      - "24224:24224/udp"
